---
title: "Tongxi's Personal Website"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Resume

Columbia University Mailman School of Public Health	New York City, NY/USA

Master of Science in Biostatistics, Public Health Data Science Track;	Expected May/2025

University of California, Santa Barbara	Goleta, CA/USA

Bachelor of Science in Psychology&Brain Sciences;

Minor in Statistical Science;	Mar/2023

UCSB Miller Lab	Goleta, CA/USA

Research Assistant	Mar/2022-Mar/2023

EEG Project: Organized video clips database categorized by emotions, improved efficiency for future experiment design to investigate the neural components of episodic memory retrieval for an event.

Crime Video Study: Recruited participants, collected responses from Qualtrics, and organized data with over 30 features using R to compare the effect of criterion manipulations on decision thresholds for freely recalled episodic events.

Jingdong(JD.com, Inc)	Remote

Data Analyst Intern	Jul/2022-Sep/2022

Conducted exploratory analysis on over 1,000 of mooncake sale data and over 65,000 fridge sale data, visualized data with bar chart, pie chart, and tree map in Python using matplotlib.
Promoted sales by analyzing sales data by brand, region. Used feature split to extract characters of fridge and mooncakes. 

Analyzed over 37 million purchasing data about costumer behaviors using funnel analysis, RFM (Recency, Frequency, Monetary) model.

Zhaopin, Zhaopin Wuhan Delivery Center	Wuhan,Hubei/China

Project Director Intern	Feb/2021-Apr/2021

Maintained log file and conducted integrity check for database consisting of 8 features related to working performance data for over 6,000 college volunteers to increase volunteer recruiting efficiency.

Improved the quality and efficiency of future hiring events by analyzing costs, timescales, and resources used in each event.
