---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(flexdashboard)
```

```{r}
data("instacart")
## kept only soy lactosefree products that were reordered
instacart = instacart |>
  filter(
    aisle_id %in%c(91),
    reordered == 1
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart |> 
  count(product_name)|>
  mutate(product_name = fct_reorder(product_name, n)) |> 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", colors = "viridis")|>
  layout(title = "Lactose Free Product Purchases",
         xaxis = list(title = "Product Name"),
         yaxis = list (title = "Count"))
```
 
Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart |> 
  count(order_hour_of_day)|>
  plot_ly(x = ~order_hour_of_day, y = ~n, color = ~order_hour_of_day,type = 'scatter', mode = 'lines', colors = "viridis")|>
  layout(title = "Lactose Free Product Purchase Hour During the dat",
         xaxis = list(title = "Hour of the day"),
         yaxis = list (title = "Count"))
```

### Chart C

```{r}
instacart |> 
  count(order_dow)|>
  plot_ly(labels = ~order_dow, values = ~n, type = 'pie') |>
  layout(title = 'Purchase during the Week',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

