---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Plotly

```{r}
library(p8105.datasets)
library(tidyverse)
library(plotly)
```
```{r}
data("instacart")
## kept only soy lactosefree products that were reordered
instacart = instacart |>
  filter(
    aisle_id %in%c(91),
    reordered == 1
  )

```

```{r}
instacart |> 
  count(product_name)|>
  mutate(product_name = fct_reorder(product_name, n)) |> 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", colors = "viridis")
```

The most purchased lactose free product is Organic unsweetened almond milk
```{r}
instacart |> 
  count(order_hour_of_day)|>
  plot_ly(x = ~order_hour_of_day, y = ~n, color = ~order_hour_of_day,type = 'scatter', mode = 'lines', colors = "viridis")
```

Poeple tend to reorder lactose free product in the middle of the day.
```{r}
instacart |> 
  count(order_dow)|>
  plot_ly(labels = ~order_dow, values = ~n, type = 'pie')
```

Monday has most reordered lactose free product.
